Задание 6. Добавилена функциональность регистрации пользователя
gpb-it-factory/bogdanov-middle-service pull request #4
Opened 2024-06-19 19:18 UTC by KimBogdanov

1. Создан проект
2. Реализована функция регистрации
3. Создана обработка ошибок
4. Написаны тесты

2024-06-25 18:35 UTC, vaganov-vadim requested changes
Привет! Всё здорово. Добавил пару небольших комментов по возможным улучшениям.

2024-06-25 18:35 UTC, vaganov-vadim commented on src/main/java/ru/gazprombank/payhub/middleservice/controller/UserController.java
> +        return String.format("Клиент %s зарегистрирован в банке", createUserRequestDto.userName());
Лучше возвращаемое значение всё-таки в какую-то модельку обернуть, чтобы это можно было расширять в будущем. Если строчку в будущем заменить на объект - то это ломающее изменение, если в объект добавить необязательное поле - неломающее.

2024-06-25 18:35 UTC, vaganov-vadim commented on src/test/java/ru/gazprombank/payhub/middleservice/controller/UserControllerIntegrationTest.java
> +        String response = userController.create(userDto);
Может быть хорошей идеей обратиться к контроллеру через какой-нибудь http-клиент. Так мы точно будем уверены, что у нас торчит endpoint и к нему можно сходить по сети.

2024-06-25 18:35 UTC, vaganov-vadim commented on src/test/java/ru/gazprombank/payhub/middleservice/controller/UserControllerIntegrationTest.java
> +                WireMock.postRequestedFor(WireMock.urlEqualTo("/v2/users"))
Вот в данном случае я предлагаю точно не проверять какой запрос и куда мы отослали, просто сравнить выходное значение. Если оно ожидаемое, то считаем, что всё ок.

2024-06-26 08:01 UTC, KimBogdanov commented on src/test/java/ru/gazprombank/payhub/middleservice/controller/UserControllerIntegrationTest.java
> +        String response = userController.create(userDto);
Надеюсь я правильно понял, что MockMvc как раз симулирует обращение к контроллеру.

2024-06-26 16:14 UTC, vaganov-vadim approved these changes
Аппрув! Добавил коммент на развитие, но там надо раскопать, если захочется, то можно сделать отдельной ПРкой.

2024-06-26 16:14 UTC, vaganov-vadim commented on src/test/java/ru/gazprombank/payhub/middleservice/controller/UserControllerIntegrationTest.java
> +    private MockMvc mockMvc;
Не уверен, что получается "интеграционность", у нас же в случае использования MockMvc никаких веб-вызовов не происходит (если не ошибаюсь). Если хочешь прям интеграцию протестить, то должен подниматься веб-сервер и должны лететь вызовы настоящих http-клиентов - RestClient/WebClient. Но это если действительно хочется.

2024-06-27 10:21 UTC, merged